### ISSUE TITLE
Proxy Passthrough

### ISSUE THREAD

**Issue by AkamaiSolutions** [x04/cclient#3]
Can not pass through proxy as empty other wise it will return `2020/10/20 02:15:05 invalid url ``, make sure to specify full url like https://username:password@hostname.com:443/`

**Comment by x04** [comment]
As a temporary workaround (if I understand this correctly) you should be able to do an empty string check on the proxy before creating the client, I will add this once I get some sleep.

**Comment by AkamaiSolutions** [comment]
> As a temporary workaround (if I understand this correctly) you should be able to do an empty string check on the proxy before creating the client, I will add this once I get some sleep.

Sounds good I appreciate it, I have also noticed that you can set any proxy you wish, invalid or not valid and it just seems to use the operating systems connect ip to make requests. Either im doing something wrong, or it just disregards proxys.

**Comment by AkamaiSolutions** [comment]
https://i.imgur.com/IUoUjax.png

**Comment by x04** [comment]
Alright pushed an update for this.
