### ISSUE TITLE
Project license? 

### ISSUE THREAD

**Issue by sleeyax** [x04/cclient#8]
Hi, I'd like to use snippets of your [client_test.go](https://github.com/x04/cclient/blob/master/client_test.go) code in my repository at [sleeyax/gotcha](https://github.com/sleeyax/gotcha). But it's unclear to me under which terms I may reuse your code, since cclient doesn't have a license.

According to [github's documentation](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository) regarding project licensing, any project that remains unlicensed automatically means all rights are reserved. That means I cannot modify or redistribute this code without explicit permission from the copyright holder (x04).

Could you either do one of the following, please?
* [Add a license](https://choosealicense.com/) to cclient (I think MIT would be a good choice for this project)
* Give me written permission to use mentioned code in my codebase

Thanks

**Comment by x04** [comment]
You can use the code any way you like.
